### ISSUE TITLE
App crashes when adding an URL without adding http:// or https:// before it

### ISSUE THREAD

**Issue by ikarago** [kesavaprasadarul/ProjectRome#3]
It crashes because it can't convert a string to an URI without the http:// and https:// before the URL. These have to be added in automatically in case these are missing.

**Comment by kesavaprasadarul** [comment]
@ikarago Anyway that http are supposed to be input by the user. Not all sites are http and not all sites redirect automatically to https.

**Comment by ikarago** [comment]
True that. In that case we should implement a check whether either of the two is there and give an error if not.

**Comment by kesavaprasadarul** [comment]
I'll work on it. 😎

**Comment by ikarago** [comment]
Fixed with a temporarily error-message. This will change in a future UI-update.
